### PR TITLE
Remove auth in error responses if it's present

### LINKED ISSUE #296: auto pr-check exposes token on some failures
**Describe the bug**

I had an incident today where `auto check-pr` made a call (trying to post a status) via `octokit` that resulted in a 404 error. This caused an exception that wasn't caught and ended up printing the response object in our CI log (which is public).

Feel free to reach out to me for the specific example. I think I have a general idea of how to go about solving this, so I'll start a PR and see where it goes. 

I also opened https://github.com/octokit/rest.js/issues/1246 because it'd really be ideal for this to be handled there so we don't have to play whack-a-mole with potential security issues. 

**Expected behavior**

`auth` header should never be included in a response or error object.

### PR DESCRIPTION
**Pull request by zephraph**
Fixes #296 

Adds exception handling and a sanitizing hook to octokit to try to prevent the leaking of auth tokens. 

# What Changed

Adds a hook to octokit that deletes the `authorization` header on all error objects before passing it throwing it again. This should ensure the token is never accidentally exposed, regardless of whether an exception is caught or not. 

# Why

If an octokit exception isn't caught then it likely will print out the authorization header in the error response which leads to leaking credentials in CI. 

Todo:

- [x] Add tests
- [x] Add docs
- [x] Add yourself to contributors (run `yarn contributors:add`)

### CODE REVIEW

**Comment by zephraph** [comment]
I think the tests are failing because Octokit is being mocked somewhere, but I'm not exactly sure where that's happening...

**Comment by hipstersmoothie** [comment]
@zephraph You'll probably need to mock out something here

https://github.com/intuit/auto/blob/master/src/__tests__/git.test.ts#L25

something like 

```js
const errorHook =  jest.fn();

jest.mock('@octokit/rest', () => {
  const instance = () => ({
 hooks: {
      error: errorHook
 },
 ...
```

**Comment by zephraph** [comment]
Yep! I'd just found it. Writing tests for this is gonna be interesting...

File: src/auto.ts [hunk 1]
```diff
@@ -308,14 +308,18 @@ export default class Auto {
...
+        await this.git.createStatus({
+          ...options,
+          ...msg,
+          target_url,
+          sha
+        } as IPRInfo);
+
+        this.logger.log.success('Posted status to Pull Request.');
+      } catch (error) {
+        this.logger.verbose.error('Failed to post status to github');
```
Comment (zephraph) [inline src/auto.ts]: The status creation call here is what actually ended up leaking the token. It resulted in a 404. This message probably should be wordsmithed a little. Should the error always print out, or only print in verbose mode?

**Comment by zephraph** [comment]
I don't have tests for the hook yet and that's the part that I'm least confident about. I'm not sure what the shape of the error object is exactly. I did add exception handling and messaging around the case when the status fails to post. I have an open question of it that should always be in the standard log or only in verbose (prCheck is verbose, pr is standard). My inclination is to have both errors logged out in standard.

**Comment by zephraph** [comment]
Okay, assuming everything is green this should be good to go. 🤞

**Comment by zephraph** [comment]
Hey @hipstersmoothie, how's it look?

File: src/auto.ts (hunk 1 above)
Comment (hipstersmoothie) [reply src/auto.ts]: I think it makes more sense to include the error in the default log. After that this PR looks good to go

Comment (zephraph) [reply src/auto.ts]:
```suggestion
        this.logger.log.error('Failed to post status to github');
```

**Comment by zephraph** [comment]
Okay, changes made!

File: src/auto.ts [hunk 2]
```diff
@@ -227,11 +227,15 @@ export default class Auto {
...
-        target_url
-      });
+      try {
+        await this.git.createStatus({
+          ...options,
+          sha,
+          target_url
+        });
+      } catch {
+        this.logger.log.error('Failed to post status to Pull Request.');
```
Comment (adierkens) [inline src/auto.ts]: If `this.git.createStatus` throws an exception, wouldn't we print: `'Failed to post status to Pull Request.'` and `'Posted status to Pull Request.'` right after it? Do we want to swallow this error?

File: src/auto.ts [hunk 3]
```diff
@@ -308,14 +312,18 @@ export default class Auto {
...
+        await this.git.createStatus({
+          ...options,
+          ...msg,
+          target_url,
+          sha
+        } as IPRInfo);
+
+        this.logger.log.success('Posted status to Pull Request.');
+      } catch (error) {
+        this.logger.log.error('Failed to post status to github');
```
Comment (adierkens) [inline src/auto.ts]: Same thing here. By catching the error and just logging a problem rather than letting the exception bubble up, the cli's exit code will 0, and we won't mark the cmd as failed: https://github.com/intuit/auto/blob/master/src/bin/auto.ts#L10 

Seeing as how these 2 methods' primary function is to set a status on a PR, I feel like we should fail the process if we can't do that.

Comment (zephraph) [reply src/auto.ts]: That's a valid point. So should we just throw an exception from here? We specifically _don't_ want to allow the caught error to continue to propagate because it could potentially expose sensitive information still.

Comment (hipstersmoothie) [reply src/auto.ts]: We could steingify the response, replace the token, parse the string and throw that.

Comment (zephraph) [reply src/auto.ts]: Well, the hook should (hopefully) do that. It could be beefed up a little. But is exposing the octokit error to the user really something that should happen anyway? It's not necessarily the friendliest of feedback. We can grab things like the response status code or error message and bubble that up in a new exception.

Comment (adierkens) [reply src/auto.ts]: 👍 Just throw an error w/ the same message as the log, and attach the response code

Comment (hipstersmoothie) [reply src/auto.ts]: @zephraph this sound okay?

**Comment by zephraph** [comment]
@hipstersmoothie, @adierkens I updated it to throw those error messages instead of just logging. Let me know if that's sufficient. Thanks for the review!

**Comment by hipstersmoothie** [comment]
@zephraph seems like some tests are failing

**Comment by zephraph** [comment]
Whoops, yeah, sorry about that. Should be fixed now.

**Comment by adierkens** [comment]
:rocket: PR was released in v4.8.11 :rocket:
